# Default values for sscd-keeper.
# -- This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- This is to override the release name.
nameOverride: ""

# -- This is to override the full name.
fullnameOverride: ""

keeper:
  # -- This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 2

  # -- This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    # -- This sets the image repository.
    repository: busybox
    # -- This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: 1.37.0

  # -- This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  # -- This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # -- This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  # -- Toggle and define pod-level security context.
  # @default -- `{}`
  podSecurityContext: {}
    # fsGroup: 2000

  # -- Toggle and define security context.
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  # keeper containers' resource requests and limits
  # ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  # -- Set container resources according to one common preset (allowed values: none, yocto, zepto, atto).
  resourcesPreset: "yocto"

  # -- Set container requests and limits for different resources like CPU or memory (essential for production workloads)
  # resources: {}
  # @ignored
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Additional volumes on the output Deployment definition.
  extraVolumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # -- Additional volumeMounts on the output Deployment definition.
  extraVolumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  # -- Node Selector for the keeper
  nodeSelector: {}

  # -- Tolerations for the keeper
  tolerations: []

  # -- Default affinity preset for the keeper
  affinity: {}
