extraRoutes:
  extra-route-1:
    enabled: true
    parentRefs:
      - name: kong
        namespace: kong-system
        group: gateway.networking.k8s.io
        kind: Gateway
    matches:
      - path:
          type: PathPrefix
          value: /extra-route-1
    filters: []
    additionalRules: []
