{{- if .Values.artifactsCache.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.artifactsCacheName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.artifactsCache.finalizers }}
  finalizers: {{ .Values.artifactsCache.finalizers | toYaml | nindent 4 }} # Finalizers are not documented on purpose as they should be kept normally
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.artifactsCache.accessModes | nindent 4 }}
  storageClassName: {{ .Values.artifactsCache.storageClassName | default "azurefile" }}
  resources:
    requests:
      storage: {{ .Values.artifactsCache.storage }}
{{- end }}