{{- if .Values.artifactsCache.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.artifactsCache.name | default (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.artifactsCache.accessMode }}
  storageClassName: {{ .Values.artifactsCache.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.artifactsCache.storage }}
{{- end }}