apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-sandbox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox.controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "agent-sandbox.controller.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: metrics
    protocol: TCP
