apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backendService.fullname" . }}-env
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{/* Static values are added last so that they override the dynamic values (avoids regression and breaking changes) */}}
  VERSION: "{{ include "backendService.imageTag" . }}"
  PORT: {{ include "backendService.applicationPort" $ | quote }}
