{{- if and .Values.secretsProvider.enabled (eq .Values.secretsProvider.provider "azure") }}
{{- range .Values.secretsProvider.azure.keyVaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "backend-service.fullname" $ }}-{{ .name }}
  labels:
    {{- include "backend-service.labels" $ | nindent 4 }}
spec:
  provider: azure
  {{- if or .secrets .keys .certificates }}
  secretObjects:
    - secretName: {{ include "backend-service.fullname" $ }}-{{ .name }}
      type: Opaque
      labels:
        {{- include "backend-service.labels" $ | nindent 8 }}
      data:
        {{- range .secrets }}
        - key: {{ .key }}
          objectName: {{ .name }}
        {{- end }}
        {{- range .keys }}
        - key: {{ .key }}
          objectName: {{ .name }}
        {{- end }}
        {{- range .certificates }}
        - key: {{ .key }}
          objectName: {{ .name }}
        {{- end }}
  {{- end }}
  parameters:
    {{- if $.Values.secretsProvider.azure.workloadIdentity.enabled }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.secretsProvider.azure.workloadIdentity.clientId | required "secretsProvider.azure.workloadIdentity.clientId is required when workloadIdentity is enabled" }}
    {{- else }}
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    {{- end }}
    keyvaultName: {{ .name }}
    tenantId: {{ $.Values.secretsProvider.azure.tenantId | required "secretsProvider.azure.tenantId is required" }}
    {{- if $.Values.secretsProvider.pollingInterval }}
    polling_interval: {{ $.Values.secretsProvider.pollingInterval }}
    {{- end }}
    objects: |
      array:
        {{- range .secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
          {{- if .version }}
          objectVersion: {{ .version }}
          {{- end }}
        {{- end }}
        {{- range .keys }}
        - |
          objectName: {{ .name }}
          objectType: key
          {{- if .version }}
          objectVersion: {{ .version }}
          {{- end }}
        {{- end }}
        {{- range .certificates }}
        - |
          objectName: {{ .name }}
          objectType: cert
          {{- if .version }}
          objectVersion: {{ .version }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}