{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-service.fullname" . }}-secrets
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }} 