{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend-service.serviceAccountName" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentity.clientId | required "serviceAccount.workloadIdentity.clientId is required when workloadIdentity is enabled" }}
  {{- end }}
{{- end }}
