{{- if .Values.prometheus.enabled }}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.labels" . -}}
{{- $selectorLabels := include "backendService.selectorLabels" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backendService.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
{{- end }}
