# CI test configuration for Kubernetes Application Alerts
prometheus:
  enabled: true
  defaultAlerts:
    kubernetesApplication:
      enabled: true
      for: "6m"
      # Test with some alerts disabled
      disabled:
        KubePodFrequentRestarts: true
        KubeContainerWaiting: true
        KubeDaemonSetNotScheduled: true
      # Test with custom rules
      customRules:
        KubePodCrashLooping:
          for: "8m"
          severity: "critical"
        KubeDeploymentReplicasMismatch:
          for: "20m"
          severity: "warning"
        KubeJobFailed:
          for: "2m"
          severity: "critical"
        KubeHpaMaxedOut:
          for: "12m"
    # Additional labels for testing
    additionalLabels:
      environment: "staging"
      team: "devops"
      alert_manager: "prometheus"
