eventBasedAutoscaling:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 2
  cron:
    timezone: Europe/Zurich
    start: 0 8 * * 1-5
    end: 0 19 * * 1-5
    desiredReplicas: "1"
  rabbitmq:
    protocol: auto
    queueName: queue.name.example
    mode: QueueLength
    value: "1"
    hostFromEnv: AMQP_URL
  customTriggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
