{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "kubernetes") }}
{{- /* Check if Cilium-specific fields are used with non-Cilium flavor */ -}}
{{- if or (hasKey .Values.networkPolicy "description") (hasKey .Values.networkPolicy "enableDefaultDeny") (hasKey .Values.networkPolicy "ingressDeny") (hasKey .Values.networkPolicy "egressDeny") }}
{{- fail "ERROR: Cilium-specific fields (description, enableDefaultDeny, ingressDeny, egressDeny) are set but networkPolicy.flavor is not 'cilium'. Please set networkPolicy.flavor to 'cilium' to use these features." }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.networkPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if hasKey .Values.networkPolicy "ingress" }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if hasKey .Values.networkPolicy "egress" }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
