{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" }}
{{- $fullName := include "common.fullname" . -}}
{{/* Default route */}}
{{- if .Values.routes.paths.default.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-default
  annotations:
    konghq.com/plugins: unique-route-metrics
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "301"
    {{- if .Values.routes.paths.default.extraAnnotations }}
    {{- toYaml .Values.routes.paths.default.extraAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ default "kong" .Values.routes.gateway.name }}
      namespace: {{ default "system" .Values.routes.gateway.namespace }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ tpl (.Values.routes.hostname) $ }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $.Values.service.port }}
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: /{{ include "webApp.routePrefix" $ }}
{{- end }}

{{/* Root route */}}
{{- if .Values.routes.paths.root.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-root
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "301"
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ default "kong" $.Values.routes.gateway.name }}
      namespace: {{ default "system" $.Values.routes.gateway.namespace }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ tpl ($.Values.routes.hostname) $ }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: {{ tpl ($.Values.routes.hostname) $ }}
            path:
              type: ReplaceFullPath
              replaceFullPath: /{{ .Values.routes.paths.root.redirect_path }}
            statusCode: 302 # Temporary Redirect, as we might change the root path in the future
            port: 443
{{- end }}

{{- else }}
{{- fail "You can't use routes without CRDs installed. Install CRDs first."}}
{{- end }}
