apiVersion: v2
type: application
icon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
maintainers:
  - name: unique-ag
    url: https://unique.ch/
name: sscsid-keeper
sources:
  - https://github.com/Unique-AG/helm-charts/tree/main/charts/sscsid-keeper
version: 1.5.0
deprecated: true
description: |
  This chart is deprecated. Unique recommends the External Secrets Operator for managing secrets in Kubernetes.
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update busybox."
