{{- if and .Values.prometheus.additionalAlerts .Values.prometheus.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.labels" . -}}
{{- $additionalLabels := dict }}
{{- if and .Values.prometheus.defaultAlerts .Values.prometheus.defaultAlerts.additionalLabels }}
{{- $additionalLabels = .Values.prometheus.defaultAlerts.additionalLabels }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullName }}-custom-alerts
  labels:
    {{- $labels | nindent 4 }}
    role: alert-rules
    {{- if $additionalLabels }}
    {{- toYaml $additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ $fullName }}-custom
      rules:
{{- range $alertName, $alertConfig := .Values.prometheus.additionalAlerts }}
{{- $mergedAlert := deepCopy $alertConfig }}
{{- if and $additionalLabels $mergedAlert.labels }}
{{- $_ := set $mergedAlert "labels" (merge $mergedAlert.labels $additionalLabels) }}
{{- else if $additionalLabels }}
{{- $_ := set $mergedAlert "labels" $additionalLabels }}
{{- end }}
        - {{- toYaml $mergedAlert | nindent 10 }}
{{- end }}
{{- end }}
