{{- if and .Values.prometheus.defaultAlerts .Values.prometheus.defaultAlerts.argocd .Values.prometheus.defaultAlerts.argocd.enabled .Values.prometheus.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.labels" . -}}
{{- $argoCDAppName := .Values.prometheus.defaultAlerts.argocd.applicationName | default .Release.Name -}}
# Requires exposing the ArgoCD metrics: https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullName }}-argocd-alerts
  labels:
    {{- $labels | nindent 4 }}
    role: alert-rules
    alertGroup: argocd
    {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ $fullName }}-argocd
      rules:
      - alert: ArgoCDApplicationDegraded
        expr: |
          argocd_app_info{health_status="Degraded", dest_namespace="{{ .Release.Namespace }}", name="{{ $argoCDAppName }}"} > 0
        for: {{ dig "ArgoCDApplicationDegraded" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: warning
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} is unhealthy"
          description: "ArgoCD application {{ $argoCDAppName }} health condition is not True for more than 5 minutes"

      - alert: ArgoCDApplicationSyncError # requires exposing SyncError condition - https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/#exposing-application-conditions-as-prometheus-metrics
        expr: |
          argocd_app_condition{name="{{ $argoCDAppName }}", condition="SyncError"} > 0
        for: {{ dig "ArgoCDApplicationSyncError" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: critical
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} has sync errors"
          description: "ArgoCD application {{ $argoCDAppName }} has sync errors for more than 5 minutes"

      - alert: ArgoCDApplicationDeletionError # requires exposing DeletionError condition - https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/#exposing-application-conditions-as-prometheus-metrics
        expr: |
          argocd_app_condition{name="{{ $argoCDAppName }}", condition="DeletionError"} > 0
        for: {{ dig "ArgoCDApplicationDeletionError" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: critical
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} has deletion errors"
          description: "ArgoCD application {{ $argoCDAppName }} has deletion errors for more than 5 minutes"

      - alert: ArgoCDApplicationInvalidSpecError # requires exposing InvalidSpecError condition - https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/#exposing-application-conditions-as-prometheus-metrics
        expr: |
          argocd_app_condition{name="{{ $argoCDAppName }}", condition="InvalidSpecError"} > 0
        for: {{ dig "ArgoCDApplicationInvalidSpecError" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: critical
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} has invalid spec errors"
          description: "ArgoCD application {{ $argoCDAppName }} has invalid spec errors for more than 5 minutes"

      - alert: ArgoCDApplicationComparisonError # requires exposing ComparisonError condition - https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/#exposing-application-conditions-as-prometheus-metrics
        expr: |
          argocd_app_condition{name="{{ $argoCDAppName }}", condition="ComparisonError"} > 0
        for: {{ dig "ArgoCDApplicationComparisonError" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: critical
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} has comparison errors"
          description: "ArgoCD application {{ $argoCDAppName }} has comparison errors for more than 5 minutes"

      - alert: ArgoCDApplicationUnknownError # requires exposing UnknownError condition - https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/#exposing-application-conditions-as-prometheus-metrics
        expr: |
          argocd_app_condition{name="{{ $argoCDAppName }}", condition="UnknownError"} > 0
        for: {{ dig "ArgoCDApplicationUnknownError" "for" "5m" (.Values.prometheus.defaultAlerts.argocd.customRules | default dict) }}
        labels:
          severity: critical
          alertGroup: argocd
          {{- with .Values.prometheus.defaultAlerts.additionalLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        annotations:
          summary: "ArgoCD application {{ $argoCDAppName }} has unknown errors"
          description: "ArgoCD application {{ $argoCDAppName }} has unknown errors for more than 5 minutes"

{{- end }}
